config/config/urls.py
from django.urls import path, include
from django.contrib import admin

import core.urls
import user.urls
import requirements.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(user.urls,namespace='user')),
    path('requirements/',include(requirements.urls,namespace='requirements')),
    path('', include(core.urls, namespace='core')),
]

config/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies',
         views.MovieList.as_view(),
         name='MovieList'),
    path('movie/<int:pk>',
         views.MovieDetail.as_view(),
         name='MovieDetail'),
    path('movie/<int:movie_id>/vote',
         views.CreateVote.as_view(),
         name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>',
         views.UpdateVote.as_view(),
         name='UpdateVote'),
    path('person/<int:pk>',
         views.PersonDetail.as_view(),
         name='PersonDetail'),

]

config/core/models.py
from django.db import models
from config import settings
from django.contrib.auth import get_user_model
from django.db.models.aggregates import Sum



class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie')


class Person(models.Model):
    first_name = models.CharField(
        max_length=140)
    last_name = models.CharField(
        max_length=140)
    born = models.DateField()
    died = models.DateField(null=True,
                            blank=True)

    objects = PersonManager()

    class Meta:
        ordering = (
            'last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
                self.last_name,
                self.first_name,
                self.born)


class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director')
        qs = qs.prefetch_related(
            'writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self):
        qs = self.get_queryset()
        qs = qs.annotate(
                vote_sum=Sum(
                    'vote__value'))
        qs = qs.exclude(
            vote_sum=None)
        qs = qs.order_by(
            '-vote_sum')
        return qs

class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G,
         'G - General Audiences'),
        (RATED_PG,
         'PG - Parental Guidance '
         'Suggested'),
        (RATED_R, 'R - Restricted'),
    )

    title = models.CharField(
        max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED)
    runtime = \
        models.PositiveIntegerField()
    website = models.URLField(
        blank=True)
    director = models.ForeignKey(
        to='Person',
        null=True,
        on_delete=models.SET_NULL,
        related_name='directed',
        blank=True)
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True)
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True)

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(
            self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie',
                           'person',
                           'name')

class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self,movie,user):
        try:
            return Vote.objects.get(movie = movie, user = user)
        except:
            return Vote(movie=movie,user=user)

class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "👍",),
        (DOWN, "👎",),
    )
    value = models.SmallIntegerField(choices = VALUE_CHOICES)
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE,)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()
    class Meta:
        unique_together = ('user','movie')

config/core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Vote,Movie

class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().
            objects.all(),
        disabled=True,
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = (
            'value', 'user', 'movie',)

config/core/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin)
from django.core.exceptions import (
    PermissionDenied)
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (
    ListView, DetailView, UpdateView,
    CreateView
)
from .forms import VoteForm
from .models import Vote,VoteManager


from .models import Movie, Person


class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'core:UpdateVote',
                    kwargs={
                        'movie_id': vote.movie.id,
                        'pk': vote.id})
            else:
                vote_form_url = (
                    reverse(
                        'core:CreateVote',
                        kwargs={
                            'movie_id': self.object.id}
                    )
                )
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = \
                vote_form_url
        return ctx


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(
            queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another '
                'users vote')
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id})
        return redirect(
            to=movie_detail_url)


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs[
            'movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={
                'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id})
        return redirect(
            to=movie_detail_url)

class MovieList(ListView):
    model = Movie
    paginate_by = 10


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()

config/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title%}
{{object.title }} - {{block.super}}
{% endblock%}
{% block main%}
<h1>{{object}}</h1>
<p class="lead">
{{object.plot}}
</p>
<h2> Directed By </h2>
 <ul>
 	{% if object.director %}
 	<li>
 		<a href="{% url 'core:PersonDetail' object.director.id %}">
 			{{object.director.last_name}},{{object.director.first_name}}
 		</a>
 	</li>
 	{% endif %}	
 </ul>
 <h2> Written By </h2>
 <ul>
 	{% for writer in object.writers.all %}
 	<li>
 		<a href="{% url 'core:PersonDetail' writer.id %}">
 			{{writer.last_name}},{{writer.first_name}}
 		</a>
 	</li>
 	{% endfor %}	
 </ul>
 <h2> Cast </h2>
 <ul>
 	{% for role in object.role_set.all %}
 	<li>
 		<a href="{% url 'core:PersonDetail' role.person.id %}">
 			{{role.person.last_name}},{{role.person.first_name}} 
 		</a>
 			 as {{role.name}}
 	</li>
 	{% endfor %}	
 </ul>
{% endblock %}
{% block sidebar %}
<div>
    This movie is rated:
    <span class="badge badge-primary">
        {{object.get_rating_display }}
    </span>
</div>
<div>
	<h2>
		Score: {{ object.score|default_if_none:"TBD" }}
	</h2>
</div>
<div>
	{% if vote_form%}
	<form method="post" action="{{ vote_form_url }}">
		{% csrf_token%}
		{{vote_form}}
		<button class="btn btn-primary">
			Vote
		</button>
	</form>
	{% else %}
		<p> Log in to vote for this movie</p>
	{% endif %}
</div>
{% endblock %}

config/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title%}
{{object.title }} - {{block.super}}
{% endblock%}
{% block main%}
<ul>
    {% for movie in object_list%}
    <li><a href="{% url 'core:MovieDetail' pk=movie.id %}"> {{movie}}</a></li>
    {% empty%}
    <li>
        No movie yet.
    </li>
    {% endfor%}
</ul>
{% if is_paginated %}
    <nav>
        <ul class="pagination">
            <li class="page-item" >
                <a href="{% url 'core:MovieList'%}?page=1" class="page-link">
                    First
                </a>
            </li>
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="{% url 'core:MovieList'%}?page={{page_obj.previous_page_number}}" class="page-link">
                    {{page_obj.previous_page_number }}
                </a>

            </li>
        {% endif %}
        <li class="page-item active">
            <a href="{% url 'core:MovieList'%}?page={{page_obj.number}}" class="page-link">
                    {{page_obj.number }}
                </a>

        </li>
        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="{% url 'core:MovieList'%}?page={{page_obj.next_page_number}}" class="page-link">
                    {{page_obj.next_page_number }}
                </a>

            </li>
        {% endif %}
        <li class="page-item active">
            <a href="{% url 'core:MovieList'%}?page=last" class="page-link">
                    Last
                </a>

        </li>
        </ul>
    </nav>
{% endif %}
{% endblock %}

config/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
{{object.first_name }}
{{object.last_name }}
{% endblock %}

{% block main %}
 <h1> {{object}} </h1>
 <h2> Actor </h2>
 <ul>
 	{% for role in object.role_set.all %}
 	<li>
 		<a href="{% url 'core:MovieDetail' role.movie.id %}">
 			{{role.movie}}
 		</a>
 			{{role.name}}
 	</li>
 	{% endfor %}	
 </ul>
 <h2> Writer </h2>
 <ul>
 	{% for movie in object.writing_credits.all %}
 	<li>
 		<a href="{% url 'core:MovieDetail' movie.id %}">
 			{{movie}}
 		</a>
 	</li>
 	{% endfor %}	
 </ul>
 <h2> Director </h2>
 <ul>
 	{% for movie in object.directed.all %}
 	<li>
 		<a href="{% url 'core:MovieDetail' movie.id %}">
 			{{movie}}
 		</a>
 	</li>
 	{% endfor %}	
 </ul>
{% endblock %}