config/config/urls.py
from django.urls import path, include
from django.contrib import admin

import core.urls
import user.urls
import requirements.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(user.urls,namespace='user')),
    path('requirements/',include(requirements.urls,namespace='requirements')),
    path('', include(core.urls, namespace='core')),
]

config/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies',
         views.MovieList.as_view(),
         name='MovieList'),
    path('movie/<int:pk>',
         views.MovieDetail.as_view(),
         name='MovieDetail'),
    path('movie/<int:movie_id>/vote',
         views.CreateVote.as_view(),
         name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>',
         views.UpdateVote.as_view(),
         name='UpdateVote'),
    path('person/<int:pk>',
         views.PersonDetail.as_view(),
         name='PersonDetail'),

]

config/requirements/urls.py
from django.urls import path
from . import views

app_name = 'requirements'

urlpatterns = [
    path('artifacttypes/<int:artifact_type_id>/',views.artifactList, name='artifact-list'),
    path('artifacttypes/<int:artifact_type_id>/create/',views.ArtifactCreate.as_view(), name='artifact-create'),
    path('artifact/<int:artifact_id>/dynamicdetails/',views.ArtifactDetailsView,name='aritifact-details'),
    path('artifact/<int:artifact_id>/details/',views.artifactFields,name="artifact-fields"),
    path('projectslist/',views.ProjectList,name='projectlist'),
    path('export/<int:project_id>/',views.TestDocument,name='export-doc'),
    path('',views.home,name="home"),


]

config/user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
path('register',views.RegisterView.as_view(),name="register"),
path('login/',auth_views.LoginView.as_view(),name='login'),
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

config/templates/base.html
<!DOCTYPE html>
<html lang="en" >
<head >
  <meta charset="UTF-8" >
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title >
    {% block title %}MyMDB{% endblock %}
  </title>
  <style>
    .mymdb-masthead {
      background-color: #EEEEEE;
      margin-bottom: 1em;
    }
  </style>

</head >
<body >
<div class="mymdb-masthead">
  <div class="container">
    <nav class="nav">
      <div class="navbar-brand">MyMDB</div>
      <a
        class="nav-link"
        href="{% url 'core:MovieList' %}"
      >
        Movies
      </a>
      <a
        class="nav-link"
        href="{% url 'requirements:home' %}"
      >
        Requirements
      </a>
      <a
        class="nav-link"
        href="{% url 'requirements:projectlist' %}"
      >
        Export Projects
      </a>
      {% if user.is_authenticated %}
      <a
        class="nav-link"
        href="{% url 'user:logout' %}"
      >
        Logout
      </a>
      {% else %}
      <a
        class="nav-link"
        href="{% url 'user:login' %}"
      >
        login
      </a>
      {% endif %}
    </nav>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-8 mymdb-main">
     {% block main %}{% endblock %}
    </div>
    <div
        class="col-sm-3 offset-sm-1 mymdb-sidebar"
    >
      {% block sidebar %}{% endblock %}
    </div>
  </div>
</div>

</body >
</html >